### ISSUE TITLE
Funny prompt for the style don't you think?

### ISSUE THREAD

**Issue by Taluen79** [EnragedAntelope/Styles-FluxDev#1]
![funny_style](https://github.com/user-attachments/assets/23eb1496-d962-4d45-a0a0-5c11f921afcd)

Funny prompt for the style don't you think? Doesn't seem to be a prompt for flux, if I'm not mistaken?

**Comment by LankyPoet** [comment]
Yikes. Sorry, that was not intentional at all, I auto generated styles coming from Mile High Styler. And it’s definitely not a style I’d purposely generate. I will look to update/remove when back to a PC. 

Thanks for raising to my attention.

**Comment by EnragedAntelope** [comment]
Censored it - thank you!

**Comment by Taluen79** [comment]
Flux is the talk right now. Fingers crossed no one scraped the example styles list to include it in some paper publication before the change. >_<

Would be hilarious!
